copy C:\Windows\DPINST.LOG
copy C:\Windows\DtcInstall.log
copy C:\Windows\IE9_main.log
copy C:\Windows\iis7.log
copy C:\Windows\msxml4-KB954430-enu.LOG
copy C:\Windows\msxml4-KB973688-enu.LOG
copy C:\Windows\PFRO.log
copy C:\Windows\setupact.log
copy C:\Windows\setuperr.log
copy C:\Windows\TSSysprep.log
copy C:\Windows\WindowsUpdate.log
copy C:\Windows\assembly\GAC_MSIL\Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging
copy C:\Windows\assembly\GAC_MSIL\Microsoft.Practices.EnterpriseLibrary.Logging
copy C:\Windows\assembly\GAC_MSIL\System.IO.Log
copy C:\Windows\assembly\NativeImages_v2.0.50727_32\System.IO.Log
copy C:\Windows\assembly\NativeImages_v4.0.30319_32\System.IO.Log
copy C:\Windows\debug\mrt.log
copy C:\Windows\debug\mrteng.log
copy C:\Windows\debug\netlogon.log
copy C:\Windows\debug\NetSetup.LOG
copy C:\Windows\debug\PASSWD.LOG
copy C:\Windows\debug\sammui.log
copy C:\Windows\debug\WIA\wiatrace.log
copy C:\Windows\inf\setupapi.app.log
copy C:\Windows\inf\setupapi.dev.log
copy C:\Windows\inf\setupapi.offline.log
copy C:\Windows\Logs\DirectX.log
copy C:\Windows\Logs\IE9_NR_Setup.log
copy C:\Windows\Logs\WU_IE9_LangPacks.log
copy C:\Windows\Logs\CBS\CBS.log
copy C:\Windows\Logs\CBS\FilterList.log
copy C:\Windows\Logs\DISM\dism.log
copy C:\Windows\Logs\DPX\setupact.log
copy C:\Windows\Logs\DPX\setuperr.log
copy C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.IO.Log
copy C:\Windows\Microsoft.NET\Framework\v2.0.50727\ngen.log
copy C:\Windows\Microsoft.NET\Framework\v2.0.50727\ngen_service.log
copy C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.log
copy C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen_service.log
copy C:\Windows\MSILOGS\Nokia_RSACertificateForIE_1.0.LOG
copy C:\Windows\Panther\cbs.log
copy C:\Windows\Panther\DDACLSys.log
copy C:\Windows\Panther\setupact.log
copy C:\Windows\Panther\setuperr.log
copy C:\Windows\Panther\UnattendGC\setupact.log
copy C:\Windows\Panther\UnattendGC\setuperr.log
copy C:\Windows\Performance\WinSAT\winsat.log
copy C:\Windows\security\database\edb.log
copy C:\Windows\security\database\edbtmp.log
copy C:\Windows\security\logs\scesetup.log
copy C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Windows\WindowsUpdate.log
copy C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\WindowsUpdate.log
copy C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\MpCmdRun.log
copy C:\Windows\SoftwareDistribution\ReportingEvents.log
copy C:\Windows\SoftwareDistribution\DataStore\Logs\edb.log
copy C:\Windows\SoftwareDistribution\DataStore\Logs\edb00063.log
copy C:\Windows\System32\catroot2\edb.log
copy C:\Windows\System32\catroot2\edb00545.log
copy C:\Windows\System32\catroot2\edb00546.log
copy C:\Windows\System32\catroot2\edb00547.log
copy C:\Windows\System32\catroot2\edb00548.log
copy C:\Windows\System32\catroot2\edb00549.log
copy C:\Windows\System32\catroot2\edb0054A.log
copy C:\Windows\System32\catroot2\edb0054B.log
copy C:\Windows\System32\config\wfplog.log
copy C:\Windows\System32\config\systemprofile\AppData\Roaming\Apple Computer\Logs\asl.115550_25Apr12.log
copy C:\Windows\System32\config\systemprofile\AppData\Roaming\Apple Computer\Logs\asl.234912_24Apr12.log
copy C:\Windows\System32\LogFiles\HTTPERR\httperr1.log
copy C:\Windows\System32\Macromed\Flash\FlashInstall.log
copy C:\Windows\System32\Msdtc\MSDTC.LOG
copy C:\Windows\System32\Msdtc\Trace\dtctrace.log
copy C:\Windows\System32\sysprep\Panther\IE\setupact.log
copy C:\Windows\System32\sysprep\Panther\IE\setuperr.log
copy C:\Windows\Temp\ASPNETSetup_00000.log
copy C:\Windows\Temp\MpCmdRun.log
copy C:\Windows\Temp\MpSigStub.log
copy C:\Windows\Temp\MSI20375.LOG
copy C:\Windows\Temp\MSI5536c.LOG
copy C:\Windows\Temp\MSIdb9ec.LOG
copy C:\Windows\Temp\Silverlight0.log
copy C:\Windows\Temp\SilverlightMSI.log
copy C:\Windows\Temp\VS80sp1-KB2251481-v3-X86-INTL\VS80sp1-KB2251481-v3-X86-INTL-msi.0.log
copy C:\Windows\Temp\VS80sp1-KB2251481-v3-X86-INTL\VS80sp1-KB2251481-v3-X86-INTL-wrapper.log
copy C:\Windows\Temp\VS80sp1-KB2538218-v2-X86-INTL\VS80sp1-KB2538218-v2-X86-INTL-msi.0.log
copy C:\Windows\Temp\VS80sp1-KB2538218-v2-X86-INTL\VS80sp1-KB2538218-v2-X86-INTL-wrapper.log
copy C:\Windows\Temp\VS80sp1-KB2548826-v4-X86-INTL\VS80sp1-KB2548826-v4-X86-INTL-msi.0.log
copy C:\Windows\Temp\VS80sp1-KB2548826-v4-X86-INTL\VS80sp1-KB2548826-v4-X86-INTL-wrapper.log
copy C:\Windows\Temp\VS80sp1-KB971090-X86-INTL\VS80sp1-KB971090-X86-INTL-msi.0.log
copy C:\Windows\Temp\VS80sp1-KB971090-X86-INTL\VS80sp1-KB971090-X86-INTL-wrapper.log
copy C:\Windows\Temp\VS80sp1-KB973673-X86-INTL\VS80sp1-KB973673-X86-INTL-msi.0.log
copy C:\Windows\Temp\VS80sp1-KB973673-X86-INTL\VS80sp1-KB973673-X86-INTL-wrapper.log
copy C:\Windows\tracing\AcroRd32_RASAPI32.LOG
copy C:\Windows\tracing\AcroRd32_RASMANCS.LOG
copy C:\Windows\tracing\AdobeARM_RASAPI32.LOG
copy C:\Windows\tracing\AdobeARM_RASMANCS.LOG
copy C:\Windows\tracing\chrome_RASAPI32.LOG
copy C:\Windows\tracing\chrome_RASMANCS.LOG
copy C:\Windows\tracing\dfsvc_RASAPI32.LOG
copy C:\Windows\tracing\dfsvc_RASMANCS.LOG
copy C:\Windows\tracing\DllHost_RASAPI32.LOG
copy C:\Windows\tracing\DllHost_RASGCW.LOG
copy C:\Windows\tracing\DllHost_RASMANCS.LOG
copy C:\Windows\tracing\Explorer_RASAPI32.LOG
copy C:\Windows\tracing\Explorer_RASMANCS.LOG
copy C:\Windows\tracing\firefox_RASAPI32.LOG
copy C:\Windows\tracing\firefox_RASMANCS.LOG
copy C:\Windows\tracing\GoogleUpdate_RASAPI32.LOG
copy C:\Windows\tracing\GoogleUpdate_RASMANCS.LOG
copy C:\Windows\tracing\helppane_RASAPI32.LOG
copy C:\Windows\tracing\helppane_RASMANCS.LOG
copy C:\Windows\tracing\IEInstal_RASAPI32.LOG
copy C:\Windows\tracing\IEInstal_RASMANCS.LOG
copy C:\Windows\tracing\IEXPLORE_RASAPI32.LOG
copy C:\Windows\tracing\IEXPLORE_RASMANCS.LOG
copy C:\Windows\tracing\IpHlpSvc.LOG
copy C:\Windows\tracing\IPNATHLP.LOG
copy C:\Windows\tracing\IPRIP.LOG
copy C:\Windows\tracing\javaw_RASAPI32.LOG
copy C:\Windows\tracing\javaw_RASMANCS.LOG
copy C:\Windows\tracing\jucheck_RASAPI32.LOG
copy C:\Windows\tracing\jucheck_RASMANCS.LOG
copy C:\Windows\tracing\jusched_RASAPI32.LOG
copy C:\Windows\tracing\jusched_RASMANCS.LOG
copy C:\Windows\tracing\KMDDSP.LOG
copy C:\Windows\tracing\mmc_RASAPI32.LOG
copy C:\Windows\tracing\mmc_RASMANCS.LOG
copy C:\Windows\tracing\NDPTSP.LOG
copy C:\Windows\tracing\NokiaLink_RASAPI32.LOG
copy C:\Windows\tracing\NokiaLink_RASMANCS.LOG
copy C:\Windows\tracing\PPP.LOG
copy C:\Windows\tracing\RASCCP.LOG
copy C:\Windows\tracing\RASEAP.LOG
copy C:\Windows\tracing\RASIPCP.LOG
copy C:\Windows\tracing\RASIPHLP.LOG
copy C:\Windows\tracing\RASIPV6CP.LOG
copy C:\Windows\tracing\RASMAN.LOG
copy C:\Windows\tracing\RASPAP.LOG
copy C:\Windows\tracing\RASPLAP.LOG
copy C:\Windows\tracing\RASTAPI.LOG
copy C:\Windows\tracing\rundll32_RASAPI32.LOG
copy C:\Windows\tracing\rundll32_RASMANCS.LOG
copy C:\Windows\tracing\setup_RASAPI32.LOG
copy C:\Windows\tracing\setup_RASMANCS.LOG
copy C:\Windows\tracing\setup_wm_RASAPI32.LOG
copy C:\Windows\tracing\setup_wm_RASMANCS.LOG
copy C:\Windows\tracing\svchost_RASAPI32.LOG
copy C:\Windows\tracing\svchost_RASCHAP.LOG
copy C:\Windows\tracing\svchost_RASDLG.LOG
copy C:\Windows\tracing\svchost_RASMANCS.LOG
copy C:\Windows\tracing\tapi32.LOG
copy C:\Windows\tracing\tapisrv.LOG
copy C:\Windows\tracing\VPNIKE.LOG
copy C:\Windows\tracing\xwizard_RASAPI32.LOG
copy C:\Windows\tracing\xwizard_RASCHAP.LOG
copy C:\Windows\tracing\xwizard_RASDLG.LOG
copy C:\Windows\tracing\xwizard_RASGCW.LOG
copy C:\Windows\tracing\xwizard_RASMANCS.LOG
copy C:\Windows\tracing\ytb_setup_RASAPI32.LOG
copy C:\Windows\tracing\ytb_setup_RASMANCS.LOG
copy C:\Windows\winsxs\poqexec.log
copy C:\Windows\winsxs\x86_microsoft-windows-com-dtc-runtime_31bf3856ad364e35_6.1.7600.16385_none_19295908c15690f3\MSDTC.LOG
