//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Applications.Translator.LocalizationStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Applications.Translator.LocalizationStrings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteContextMenuItem {
            get {
                return ResourceManager.GetString("DeleteContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error translating the text. Please check your network connectivity and try again..
        /// </summary>
        public static string ErrorTranslating {
            get {
                return ResourceManager.GetString("ErrorTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phrases.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phrases.
        /// </summary>
        public static string HistoryLowerCase {
            get {
                return ResourceManager.GetString("HistoryLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string LanguageFrom {
            get {
                return ResourceManager.GetString("LanguageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string LanguageTo {
            get {
                return ResourceManager.GetString("LanguageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say It.
        /// </summary>
        public static string SayIt {
            get {
                return ResourceManager.GetString("SayIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating....
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en,fr,it,de,es.
        /// </summary>
        public static string SupportedLanguages {
            get {
                return ResourceManager.GetString("SupportedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your Microsoft Translator Bing API AppID] - see http://go.microsoft.com/fwlink/?LinkID=207245.
        /// </summary>
        public static string TextToSpeechID {
            get {
                return ResourceManager.GetString("TextToSpeechID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.microsofttranslator.com/v2/Http.svc/Speak?appId={0}&amp;from={2}&amp;language={3}&amp;text={1}.
        /// </summary>
        public static string TextToSpeechURI {
            get {
                return ResourceManager.GetString("TextToSpeechURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your Microsoft Translator Bing API AppID] - see http://go.microsoft.com/fwlink/?LinkID=207245.
        /// </summary>
        public static string TextTranslateID {
            get {
                return ResourceManager.GetString("TextTranslateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.microsofttranslator.com/v2/Http.svc/Translate?appId={0}&amp;text={1}&amp;from={2}&amp;to={3}.
        /// </summary>
        public static string TextTranslateURI {
            get {
                return ResourceManager.GetString("TextTranslateURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSLATOR.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
    }
}
